#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
    path: /authentication_token
    methods: ['POST']
app_register:
    path: /register
    controller: App\Controller\RegistrationAction
