# api/config/schema.yaml
# The list of types and properties we want to use
id:
    generationStrategy: uuid
    writable: true
types:
    Person:
        properties:
            name: ~
            familyName: ~
            givenName: ~
            additionalName: ~
            address: ~
    PostalAddress:
        # Disable the generation of the class hierarchy for this type
#        parent: false
        properties:
            # Force the type of the addressCountry property to text
            addressCountry: { range: "Text" }
            addressLocality: ~
            addressRegion: ~
            postOfficeBoxNumber: ~
            postalCode: ~
            streetAddress: ~
