author:  Maxim Yalagin <yalagin@gmail.com>
id:
    generationStrategy: uuid
    writable: true
#useInterface:         true
types:
    Thing:
        properties:
            name: ~
    Person:
        parent: Thing
        properties:
            familyName: ~
            givenName: ~
            additionalName: ~
            address: { range: "PostalAddress" }
            birthDate: ~
            follows:  { range: "Person" }
            knows:  { range: "Person" }
            gender: ~
            height: { range: "QuantitativeValue" }
            knowsLanguage: 
                range: "Language"
            nationality: { range: "Country" }
            weight: { range: "QuantitativeValue" }
    PostalAddress:
        properties:
            addressCountry: { range: "Country" }
            addressLocality: ~
            addressRegion: ~
            postOfficeBoxNumber: ~
            postalCode: ~
            streetAddress: ~
    QuantitativeValue:
        properties:
            value: ~
            unitCode: ~
    Place:
        properties:
            address: { range: "PostalAddress" }
    Country:
        properties:
            name: ~
    Language:
        properties:
            name: ~
            alpha2:
                range: "Text"
                ormColumn: "length=2"
            alpha3: 
                range: "Text"
                ormColumn: "length=3"
    AggregateRating:
        properties:
            itemReviewed: ~
            ratingCount:
                range: "Number"
            reviewCount:
                range: "Number"
            ratingValue:
                range: "Number"
    Rating:
        properties:
            author: { range: "Person" }
            ratingValue: {range: "Number"}
    Review:
        properties:
            author: { range: "Person" }
            itemReviewed: { range: "Person" }
            name: ~
            reviewBody: ~
            reviewRating: { range: "Rating" }
            publisher: { range: "Person" } #"@type": "Organization", "name": "Washington Times"
    ExerciseAction:
        properties:
            exercisePlan: 
                range: "ExercisePlan"
            exerciseType: ~
            sportsEvent: 
                range: "SportsEvent"
            actionStatus: 
                range: "ActionStatusType"
            agent:
                range: "Person" #who did it 
            endTime: ~
            startTime: ~
            error: {range: "Thing"} # failed 
            instrument: {range: "Thing"} # part of body
            object: {range: "Thing"} #equipment
            result: {range: "Thing"} #complited
            target: {range: "EntryPoint "} #how many reps
