author:  Maxim Yalagin <yalagin@gmail.com>
id:
    generationStrategy: uuid
    writable: true
types:
    Thing:
        properties:
            name: ~
    Person:
        properties:
            familyName: ~
            givenName: ~
            additionalName: ~
            address: { range: "PostalAddress" }
            affiliation: { range: "Organization" } 
            birthDate: ~
            birthPlace: { range: "Place" }
            homeLocation: { range: "Place" }
            duns: ~
            follows:  { range: "Person" }
            knows:  { range: "Person" }
            gender: ~
            hasOccupation: { range: "Occupation" }
            height: { range: "QuantitativeValue" }
            jobTitle: ~
            knowsLanguage: 
                range: "Language"
                cardinality: "(*..*)"
            nationality: { range: "Country" }
            telephone: 
                unique: true
            weight: { range: "QuantitativeValue" }
            worksFor: { range: "Organization" }
    PostalAddress:
        properties:
            addressCountry: { range: "Country" }
            addressLocality: ~
            addressRegion: ~
            postOfficeBoxNumber: ~
            postalCode: ~
            streetAddress: ~
    QuantitativeValue:
        properties:
            value: ~
            unitCode: ~
    Place:
        properties:
            address: { range: "PostalAddress" }
    Country:
        properties:
            name: ~
    Organization:
        properties:
            name: ~
#            address: { range: "PostalAddress" }
#            aggregateRating: { range: "AggregateRating" }
#            alumni: { range: "Person" }
#            areaServed: { range: "AdministrativeArea" }
#            awards: ~
#            contactPoints: { range: "ContactPoint" }
#            department: { range: "Organization" }
#            dissolutionDate: ~
#            email: ~
#            employees: { range: "Person" }
#            founders: { range: "Person" }
#            foundingDate: ~
#            globalLocationNumber: ~
#            hasOfferCatalog: { range: "OfferCatalog" }
#            knowsLanguages: { range: "Language" }
#            knowsAbout: { range: "Thing" }
#            location: { range: "Place" }
#            logo: { range: "ImageObject" }
#            members:  { range: "Person" }
#            naics:  { range: "Text" }
#            review:  { range: "Review" }
#            slogan: ~
#            telephone: ~
#            legalName: ~
#            leiCode: ~
#            isicV4: ~
#            vatID: ~
#            duns: ~
    Language:
        properties:
            name: ~
            alpha2:
                range: "Text"
                ormColumn: "length=2"
            alpha3: 
                range: "Text"
                ormColumn: "length=3"
    Occupation:
        properties:
            name: ~
            #            occupationalCategory: ~
            #            responsibilities: ~
            #            skills: ~
            sameAs: ~
#            estimatedSalary: ~
#            occupationLocation: ~
